### ISSUE TITLE
geolocation error handling

### ISSUE THREAD

**Issue by iubrain** [iubrain/distance#1]
Currently if you just navigate to the [page](http://iubrain.github.io/distance/) and click the button, you get the pop-up bar asking for permission to use your location.

However, after agreeing and clicking the button, the page does not update with the distance.

Refreshing the page, and *then* clicking the button gives the desired result.

Solution: add success/failure callbacks to `getloc()`

**Comment by iubrain** [comment]
error handling added, but the bug persists.

**Comment by hoosierEE** [comment]
auto-updating seems to sidestep this issue.
